"""Expand VitalSign model with detailed fields

Revision ID: 02947fa2b623
Revises: 74151444ec60
Create Date: 2025-04-13 04:44:06.959928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02947fa2b623'
down_revision = '74151444ec60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vital_signs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mean_arterial_pressure', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('pain_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('blood_glucose', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('height', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('weight', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('bmi', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('level_of_consciousness', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('intracranial_pressure', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('cerebral_perfusion_pressure', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('urine_output', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('central_venous_pressure', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('pap_systolic', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('pap_diastolic', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cardiac_output', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('svo2', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('etco2', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('pao2_fio2_ratio', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vital_signs', schema=None) as batch_op:
        batch_op.drop_column('pao2_fio2_ratio')
        batch_op.drop_column('etco2')
        batch_op.drop_column('svo2')
        batch_op.drop_column('cardiac_output')
        batch_op.drop_column('pap_diastolic')
        batch_op.drop_column('pap_systolic')
        batch_op.drop_column('central_venous_pressure')
        batch_op.drop_column('urine_output')
        batch_op.drop_column('cerebral_perfusion_pressure')
        batch_op.drop_column('intracranial_pressure')
        batch_op.drop_column('level_of_consciousness')
        batch_op.drop_column('bmi')
        batch_op.drop_column('weight')
        batch_op.drop_column('height')
        batch_op.drop_column('blood_glucose')
        batch_op.drop_column('pain_score')
        batch_op.drop_column('mean_arterial_pressure')

    # ### end Alembic commands ###
