"""Increase User password_hash length

Revision ID: 156e72ea5f5a
Revises: 2e4f9427984e
Create Date: 2025-04-09 02:51:03.864634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '156e72ea5f5a'
down_revision = '2e4f9427984e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)

    # ### end Alembic commands ###
