"""Add Admission model

Revision ID: bacf8a1a1ae1
Revises: bde6d0697b85
Create Date: 2025-04-08 22:02:08.861334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bacf8a1a1ae1'
down_revision = 'bde6d0697b85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('admitting_physician_id', sa.Integer(), nullable=True),
    sa.Column('admission_date', sa.DateTime(), nullable=False),
    sa.Column('discharge_date', sa.DateTime(), nullable=True),
    sa.Column('reason_for_visit', sa.Text(), nullable=True),
    sa.Column('current_location', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['admitting_physician_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admissions_patient_id'), ['patient_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admissions_patient_id'))

    op.drop_table('admissions')
    # ### end Alembic commands ###
