"""Add MedicalTerm model

Revision ID: e4794208dd4b
Revises: 4c0026e74ea5
Create Date: 2025-04-11 02:19:03.961818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4794208dd4b'
down_revision = '4c0026e74ea5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medical_terms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=150), nullable=True),
    sa.Column('term_en', sa.String(length=255), nullable=False),
    sa.Column('term_ka', sa.String(length=255), nullable=False),
    sa.Column('pronunciation_ka', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('medical_terms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medical_terms_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_medical_terms_term_en'), ['term_en'], unique=False)
        batch_op.create_index(batch_op.f('ix_medical_terms_term_ka'), ['term_ka'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medical_terms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medical_terms_term_ka'))
        batch_op.drop_index(batch_op.f('ix_medical_terms_term_en'))
        batch_op.drop_index(batch_op.f('ix_medical_terms_category'))

    op.drop_table('medical_terms')
    # ### end Alembic commands ###
